### ISSUE TITLE
New features in patch versions

### ISSUE THREAD

**Issue by misund** [samchon/typia#1075]
## Question

I've noticed that Typia sometimes includes feature additions in patch upgrades. For example, version 6.0.6 includes the commit `feat: Migrate to ESM and use tsup for building`, and version 6.0.4 includes `Feat: apply RFC3339 standard to typia.tags.Format<"date-time"|"date"|"time">`.

Typically, I would expect new features to trigger a minor version bump rather than just a patch version bump, meaning these feature additions would result in a 6.1.0 release.

Could you please explain your strategy for deciding how to bump the version number?

**Comment by samchon** [comment]
I've published major update only when break change that cannot be compatible with previous. Also, performed minor update when new feature comes, but still compatible with previous versions. About the patch update case, I did it when fixing bug, or some enhancement but no user interface level change.

About the RFC3339 issue, I did patch update because it does not change the user level interface. Also about the ESM issue, I didn't think that it is a minor patch story because ESM was not supported in the past, but building independent ESM file for shrinking bundling size.

However, I cannot assure myself that I have always strictly observed semver according to this principle. Also, about the RFC and ESM independent bundling issues, I understand that someone may think different with me.

**Comment by misund** [comment]
Thank you for your quick reply (and while I'm at it: also thank you for your open source contributions in this project over time).

It seems that we agree in theory about the versioning, even if we might differ on the implementation into practice.

If I may be so bold as to make a recommendation, I propose to trigger a new minor version whenever the release includes a `feat: ` commit.

**Comment by samchon** [comment]
You are right, I had to upgrade minor patch after adding `UniqueItems`, but I missed it.
