### ISSUE TITLE
Typia is failing to consider or types for a key, it defaults to the first option and validates against that instead of considering other options on the key

### ISSUE THREAD

**Issue by gurbaj5124871** [samchon/typia#1100]
### 📝 Summary
Typia is failing to consider or types for a key, it defaults to the first option and validates against that instead of considering other options on the key

  - **Typia Version**: 6.0.6
  - **Expected behavior**:  Should return empty array of errors
  - **Actual behavior**:  Returning the below errors:
  ```
  [
  {
    "path": "$input.data.grant.authorization[\"@type\"]",
    "expected": "\"/cosmos.staking.v1beta1.StakeAuthorization\"",
    "value": "/cosmos.authz.v1beta1.GenericAuthorization"
  },
  {
    "path": "$input.data.grant.authorization.allowList",
    "expected": "__type.o5"
  },
  {
    "path": "$input.data.grant.authorization.authorizationType",
    "expected": "string"
  }
]
  ```

I have the below typescript interface:
```
export interface Parent {
  type: string;
  data: {
    granter: string;
    grantee: string;
    grant:
      | ChildOne
      | ChildTwo;
  };
}

interface ChildOne {
  authorization: {
    '@type': '/cosmos.staking.v1beta1.StakeAuthorization';
    allowList: {
      address: string[];
    };
    authorizationType: string;
  };
  expiration?: string;
}

interface ChildTwo {
  '@type': '/cosmos.authz.v1beta1.GenericAuthorization';
  msg: string;
}
```

> #### Example Link
> https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGQKYAekscwAdjJVBqgMaVwAKqUlZnADeZOAmSUAXHADOMKEwDm5cQBNUMVDNHjxSqKmasZ8xYxVi9Boy2lyFy1dcPMpVvXAA+cAMIALYAAbNQB5RkoPPR8A4LUAFQB3CGcAX3JUiiYWNk5uWJDw7l04VABXGH9oYAAvTWAIRh0ogHIAAUJKFpkWgHoOCFkQQYA6eVQAa2URgDcARgAjSi05kYBlLQnKAEEKqsU6mAbGFudxVCCgiESAGWB5Zs9ztTUBWVlTRwsAbQBdM7g6Si5Uq1UOx3ikk+5ks4iB4hoKEMR0aAH5oU4yJkyNlWOwuH5AiEkhARFZ2p1unA+gMhqMQf4arNFstUKsAOKCVjADi7UEHeqNU5WECyJQYiwZCi9XoAWnlsrIMrgAEk1kq5QqyANGPI4BotHAALxkzydHq04ayEYMpnzJYrEYAWTF7NcMBaABoogbtKanvp3SZqZbBnNGIyMGUlBcMCAAEwATn8MAwlDAAHYYNQAMyIACsGH8IAAHAArfwTWT5jiIAAsJdkQS9UU8NmM9haodkc0Q2ZqZUSqH8FfelAm1AmE0Tsn4QRqAAZ8xUZmmZiX82WAGyMHM1FsBwO2R6HzwMsGCpr+08BimSKk0wZWm17O0sx2ciKKXl7C8ok7ejeh6iuK1L9E+oxqPcjgLBUxzMg6bLOmKADqwCVK8qCJAAIpQQSUDGMDQAASpQQ5QGoLStoeqSAUBcCIsAyLHD08YLvG+ayguW6ynMczxPG8ZSAuC7CQuABaVGnpkniZEC2qNHqbxlEE8AmoQaCzBcwAGpQAA8fACMwAB8AAUvoAJTkDqsgQPhIxXEopnKapVlkEAA

### 💻 Code occuring the bug
```typescript
import typia from "typia";

const data = {
    type: 'cosmos.authz.v1beta1.MsgGrant',
    data: {
        granter: 'cosmos1nhzfugalfm29htfep7tx3y5fhm8jhks5cy48sl',
        grantee: 'cosmos1ytxzuwahjhssekxkk9sarlz05utvfev85j6n3z',
        grant: {
            authorization: {
                '@type': '/cosmos.authz.v1beta1.GenericAuthorization',
                msg: '/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward'
            },
            expiration: '2025-06-11T22:00:00Z'
        }
    }
};

const result = typia.validate<Parent>(data);
console.log(result);
```

Result of above code:
```
[LOG]: {
    success: false, 
    errors: [{
        path: "$input.data.grant.authorization[\"@type\"]", 
        expected: "\"/cosmos.staking.v1beta1.StakeAuthorization\"", 
        value: "/cosmos.authz.v1beta1.GenericAuthorization"
      }, {
        path: "$input.data.grant.authorization.allowList", 
        expected: "__type.o2", 
        value: undefined
      }, {
        path: "$input.data.grant.authorization.authorizationType", 
        expected: "string", 
        value: undefined
      }], 
    data: undefined
  }
```

**Comment by samchon** [comment]
It's because your value is actually wrong typed.

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGQKYAekscwAdjJVBqgMaVwAKqUlZnADeZOAmSUAXHADOMKEwDm5cQBNUMVDNHjxSqKmasZ8xYxVi9Boy2lyFy1dcPMpVvXAA+cAMIALYAAbNQB5RkoPPR8A4LUAFQB3CGcAX3JUiiYWNk5uWJDw7l04VABXGH9oYAAvTWAIRh0ogHIAAUJKFpkWgHoOCFkQQYA6eVQAa2URgDcARgAjSi05kYBlLQnKAEEKqsU6mAbGFudxVCCgiESAGWB5Zs9ztTUBWVlTRwsAbQBdM7g6Si5Uq1UOx3ikk+5ks4iB4hoKEMR0aAH5oU4yJkyNlWOwuH5AiEkhARFZ2p1uvh+oNhrIRiD-DVZotlqhVgBxQSsYAcXagg71RqkKwgWRKDEWDIUXq9AC0CrlZFlcAAkmtlfLFWQBox5HANFoZHwBEIALxkzydHoDIajRnM+ZLFYjACy4o5rhgLQANFFDdpLU99F6THAWra6XNGEyMGUlBcMCAAEwATn8MAwlDAAHYYNQAMyIACsGH8IAAHAArfwTWTFjiIAAsFdkQV9UU8NmM9gjtMGc0Q+ZqZUSqH8NfelAm1AmE1Tsn4QRqAAZixUZlmZhXi1WAGyMAs1DvBkO2R6nzyMsFCppBy-BimSKl9SP2vaO1kurkRRR8vY3iiJx+g+p5ihK4Y0na9JqPcjgLBUxwss67JuuKADqwCVK8qCJAAIpQQSUAmMDQAASpQY5QGoLSdqeqQgaBcCIsAyLHD0yYrsmxZyiue5ynMczxMmyZSCuK5iSuABatGXqkcj1LIGDAJQsiEnEJJRJkQI6o0+pvGUQTwBahBoCM9wADwmoIMAAHwABQBgAlOQuqyBAREjFcSj2QZRkuWQQA

![image](https://github.com/samchon/typia/assets/13158709/e5091b74-48cb-4454-9600-002bb27aa88f)
