### ISSUE TITLE
Proposal: rename functions `assert` -> `ensure` & `assertGuard` -> `assert`

### ISSUE THREAD

**Issue by ryoppippi** [samchon/typia#1163]
### Prooposal

Rename the followin functions
-  `assert` -> `ensure`
- `assertGuard` -> `assert`

### Why

- Since `assertGuard` works the same way as the assertion function in TypeScript, I think the name `assert` is appropriate.
- The `Typia` `assert` function has a return value of `T`, so rather than being an assert function, it behaves more like "check the value, return the value as is if it is OK, throw an error if it is not". Therefore, the name "ensure" is more appropriate.

This is a breaking change, so when we change it, it will be included in v7

**Comment by samchon** [comment]
About the `assert<T>()` function, it has come from [`typescript-is`](https://github.com/woutervh-/typescript-is), with the returning `T` value definition. I know that `typia.assertGuard<T>()` function is more proper for the `assert` word meaning, but I've to consider the previous `typia` and [`typescript-is`](https://github.com/woutervh-/typescript-is) users.

Your strategy is too much critical change that every previous `typia` and [`typescript-is`](https://github.com/woutervh-/typescript-is) users. They must be confused at the next v7 major patch if I accept your suggestion. I just hope the v7 major update to take critical change only in the compiler API level.

Shuffling functions' names must be careful, and this is not acceptable case.

**Comment by ryoppippi** [comment]
I'm really new user, so I didn't know about the history, so I was curious why `Typia` uses that naming.
I prefer to use a library called [unknownutil](https://github.com/jsr-core/unknownutil) in addition to `Typia`, and I used naming like proposal there, so I made this suggestion


Thank you for answering.
Yeah this is too critical change, I know.

**Comment by samchon** [comment]
https://dev.to/samchon/good-bye-typescript-is-ancestor-of-typia-20000x-faster-validator-49fi

`typia` has started from faster JSON stringify function only (at that time's name was `typescript-json`), and I'd developed [`nestia`](https://nestia.io/) to utilize both `typescript-json` and `typescript-is` libraries to compose easier and faster NestJS decorators like [`@TypedRoute.Post()`](https://nestia.io/docs/core/TypedRoute/) and [`@TypedBody()`](https://nestia.io/docs/core/TypedBody/) functions.

The reason why `typescript-json` had been renamed to `typia` and started supporting validations instead of `typescript-is` is, `typescript-is` had stopped maintaining at that time. `typescript-is` had several major bugs related to validation, and I initially tried to contribute to `typescript-is`. However, as `typescript-is` was discontinued, I've developed my own validator and renamed it `typia`.

Since I embrace `typescript-is` and have inherited maintenance from the `typescript-is` owner, I cannot afford to change the `assert()` function name. This is especially true because if you look at npm trends, you can see that the majority of `typia` users came from `typescript-is`.

<img width="976" alt="image" src="https://github.com/user-attachments/assets/2bddb887-5410-4264-a973-cb31fe975364">
