### ISSUE TITLE
Can the `typia.llm.schema()` function return the given types back?

### ISSUE THREAD

**Issue by ismailkarsli** [samchon/typia#1445]
[TS Play example](https://www.typescriptlang.org/play/?moduleResolution=99&target=99&jsx=0&module=199#code/JYWwDg9gTgLgBAbzgUQDYE8DOwCGcC+cAZlBCHAOQCmG2OFAUKJLHPCWZQALYB2AxqhzAoAehjowVAEYQAHo2bR4STPwAWVEHkIdyAIglhco1MGmnUIfQwajRcACrrgmOBF5U4UKjACuULxujgDy0gBWVPwwADxIcgBcTgDKMFDAvADmBAB8bJJUADRwAO4uGnD8ZGA4MOaoXiXAMOpwmcAAblS8+VIMVUHwRjLyyRpaeAC8bAB0YZHRABQIdg5w6wB6APwM64mzqelZiwCUDPhnq06SuN6+AUFweJndVFA4qL2NzeoQfvDtLo9YZwMwAay8AEkADJWMaabQANQAzHAMmwXG4qHIcOAGv0PJghjccPCJnBpmoETg4nB9kSjtl8MV9MiZgAGfQ5U4Abiu6zg2yuAGEcMDMe5PE9UJgIHd-IE4LKQL4XFlQcAIRiqJgqDt7JVCcTjKTxtokjC4WacCiZpD5lFYvELbCQGSkWzIYcMkyclcBkTerh3TgXVbqSjafS0j7cnADbVQVQcIGWl5Ad0vmiYLrUERbAaAII9bG4sANOB+XWVFNUBieEooWi4U67OAzF4wRYUUQUYqLaJyE4UvIrAWVGByGY1d4gTBt9YGwU7dbMheIdfrGe4zBJYayOQh9dLoXj-Bts5AA)

As can be seen from the example, Typebox returns types for the schemas it creates. However, Typia returns a generic type like `ILlmSchemaV3` or `IChatGptSchema`. Which is union of subtypes. This prevents the `typia.llm.schema()` function from being type safe. Could this feature be added?

**Comment by samchon** [comment]
Considering purpose of the `typia.llm` module that has been designed to support the LLM function calling and LLM structured output features, there is no reason to add the original generic argument type of TypeScript to the returning LLM function calling schema. Why it required?

**Comment by ismailkarsli** [comment]
This is required to make Elysia.js compatible with Typia. It's certainly not mandatory for the LLM context, but it's also a nice feature to have without any overhead.

I opened this issue because I believe that wrapping the given type in a generic would not cause much trouble.

However, if you think it is invalid or burdensome, feel free to close the issue 👍

**Comment by samchon** [comment]
As the llm schema types are coming from the `@samchon/openapi`, it is not possible to adjust the original typescript type as optional as `typia.json.schemas()` function does.

If you need the JSON schema not for the LLM function calling reason but for Swagger document composition, it would better to study how to adjust the `$ref` type to the target Swagger document (`OpenApi.IComponents`). Otherwise, consider `OpenApiTypeChecker.escape()` function calling of the `@samchon/openapi` library.

Anyway, you should use the `typia.json.schemas()` function.

**Comment by ismailkarsli** [comment]
But it has no singular schema generation :) https://github.com/samchon/typia/issues/1343

But I don't want to complain. I use Typia everywhere and I'll try to use what I have now. Thanks.
