### ISSUE TITLE
Optional function properties result in errors if they are defined in an object

### ISSUE THREAD

**Issue by wfdewith** [samchon/typia#378]
### Summary
  - **SDK Version**: 3.3.37
  - **Expected behavior**: An object with a function property should be valid instance of an interface where the function property is optional
  - **Actual behavior**:  The object is not a valid member

### Code occuring the bug
```typescript
import TSON from "typescript-json"

interface Foo {
	bar: number;
	baz?: (quz: number) => number;
}

function id(i: number): number {
	return i;
}

console.log(TSON.is<Foo>({ bar: 2, baz: id }))
console.log(TSON.validate<Foo>({ bar: 2, baz: id }))
console.log(TSON.assert<Foo>({ bar: 2, baz: id }))

console.log(TSON.is<Foo>({ bar: 2 }))
console.log(TSON.validate<Foo>({ bar: 2 }))
console.log(TSON.assert<Foo>({ bar: 2 }))
```

**Comment by samchon** [comment]
```typescript
interface Date {
    getVarDate: () => VarDate;
}
```

This problem is caused by `Date` type bug of `TypeScript`.

As you can see from the above code, `TypeScript` has defined the `getVarDate` member that never exists on the `Date` class instance. To avoid such `TypeScript`'s own bug, I supported the `functional: false` option, but the option is causing endless bugs. I updated a new version `v3.3.38` to avoiding this issue's bug, but another bug can be occurred continuously.

Therefore, avoid defining functional property in object type until #372 to be published. 

After the #372 patch, I'll erase the `functional: false` option.

**Comment by samchon** [comment]
For a fundamental solution, wrote an issue on the TypeScript repo:

https://github.com/microsoft/TypeScript/issues/51636
