### ISSUE TITLE
Support user-supplied additional type validation

### ISSUE THREAD

**Issue by TheYarin** [samchon/typia#550]
## Feature Request

- The problem I'm trying to solve:

    - Sometimes validation cannot be easily defined solely using a typescript type. To address that, you added support for validation based on JSDoc annotations, but this is a partial solution, as it only addresses a few specific (yet common) scenarios, such as `email`, `ipv6`, `@length`, `@minimum`, `@pattern` etc. There is still a need for truely custom validation.

- The suggested solution:

    - Allow registering custom validation functions for a given type

    - The custom validation function will be executed after typia's generic type validation succeeds

    - To validate type `T`, The function's signature will be `(t: T) => boolean`

    - After registration, any attempt to validate type `T` will go through the custom validation as well

    - Remaining open questions:

        - How will the registration look like?

            - Maybe add another typia function like `registerCustomValidator<T>(validator: (t: T) => boolean);` that users will call right after the type definition?

        - In case of the custom validation failing, how should an error message be delivered to the user, if at all?

- Example:

    ```typescript
    import {registerCustomValidator} from 'typia'
    
    export type MyType = {
    // ...
    };
    
    registerCustomValidator<MyType>(myType => true);
    ```

**Comment by samchon** [comment]
Good idea, I will try your solution

**Comment by samchon** [comment]
I tried your solution, but it was hard for me to syncing the custom validation logic, because `typia` constructs validation logic in the compilation level, and can't sure which file (validation code vs custom validation logic insertion code) would be compiled earlier.

Therefore, studying your suggestion, I've decided how to support the custom validation function.

I'll write the new solution as a new article. Thanks for suggestion.
