### ISSUE TITLE
Overwrite current directory

### ISSUE THREAD

**Issue by gwendalF** [samchon/typia#583]
Currently to be able to use typia in frontend project using Vite and some specific transformers (Svelte) we need to use the generate. The issue is we now have 2 folders with jsut the transformation with is different. I would like to be able to overwrite the current directory to use typia generated code. 

for example `npx typia generate --input src --output src --project tsconfig.json` 

Otherwise is there a possibility to have a vite plugins to be able to use typia in vite project?

**Comment by samchon** [comment]
I do not recommend overwriting because it is irreversible.

If you want to use transform mode without generation in `vite`, you can do it like below. 

However, because of `vite`'s bug, it can't adjust code editing in dev mode just by one save. It requires double save.

https://github.com/samchon/typia/wiki/Setup#vite
