### ISSUE TITLE
New tsconfig strictNullChecks check doesn't respect tsconfig extends

### ISSUE THREAD

**Issue by jasperlin451** [samchon/typia#652]
## Bug Report

Our project's tsconfig extends a base tsconfig that sets `strict:true`.

```bash
npx tsc --showConfig | jq .compilerOptions.strict
true
```

It seems like the newest check errors out w/ 
```
Error: Error on "tsconfig.json": typia requires `compilerOptions.strictNullChecks` to be true.
```

**Comment by samchon** [comment]
Can you make a reproducable repo?

**Comment by samchon** [comment]
I did same setting, but such error does not occur.

Check `strictNullChecks` property instead of `strict`. It may configured as `false`.

**Comment by jasperlin451** [comment]
```
npx tsc --showConfig | jq .compilerOptions.strictNullChecks
null
```

**Comment by jasperlin451** [comment]
https://replit.com/join/tniwjdaqve-jasperlin14

I believe it breaks if the tsconfig extends something installed as a node_module instead of a relative file path.

```
{
  "extends": "@tsconfig/node-lts/tsconfig.json"
}
```

**Comment by samchon** [comment]
I tested same code on `stackblitzs`, and there had not been any problem.

As it works fine even in Github Actions, I think it seems a problem of `replit` \o/.

  - Stackblitzs: https://stackblitz.com/github/samchon/typia-issue-652
  - Github Actions: https://github.com/samchon/typia-issue-652/actions/runs/5231286478/jobs/9445341706#step:5:16

**Comment by barbeque-squared** [comment]
I am hitting this as well. I don't use `replit`; this is in a plain npm monorepo. The error is thrown from `transform.ts`, but I believe `ts.readConfigFile` is the real culprit which is in `TypiaProgrammer.ts`, see also the discussion on https://github.com/kulshekhar/ts-jest/issues/245

Very basic file structure:
```
myapp/package.json
myapp/some-script.ts
myapp/tsconfig.json
config-shared/base.json
config-shared/package.json
package.json
```

```
// package.json
{
  "workspaces": ["myapp", "config-shared"]
}
```

```
// config-shared/package.json
{
  "name": "@repo/config-shared",
  "exports": {
    "./base": "./base.json"
  },
}
```

```
// myapp/some-script.ts
await TypiaProgrammer.build({
  input: someDir,
  output: someOtherDir,
  project: 'tsconfig.json',
})
```

`config-shared/base.json` defines a bunch of stuff I use in all my apps, one of them is `strict: true`.
`myapp/package.json` has a devDependency on `"@repo/config-shared": "*"`

## This does not work
```
// myapp/tsconfig.json
{
  "extends": "@repo/config-shared/base"
}
```

## This does work (but is not desired)
```
// myapp/tsconfig.json
{
  "extends": "@repo/config-shared/base",
  "compilerOptions": {
    "strict": true
  }
}
```

I can try to bang out a reproducable repro repository tomorrow or next week (or later, depends a bit on when you reply) if the above is not enough to reproduce. But since this one is already closed did you want that on this issue or a new one and reference this one?
