### ISSUE TITLE
Feedback for “Setup”

### ISSUE THREAD

**Issue by bogeeee** [samchon/typia#689]
`npx typia setup`

Also, you could tell us, how this works under the hood and what does it modify and how can you do it manually. For me personally, i wouldn't like having some script magically modifying my configs / build chain and i would at least have a manual option.

What about just using the "slow" validator functions like  `is` ? Is that also covered by the transform/AOT mode ? I guess: Yes. But mention that please. Or mention that it in the introduction page.

This sentence under "Generation"

> Instead, you should utilize the generation mode.

is somehow redundant and confused me (what was that mode again that it's woth beeing mentioned now)

Jeah, lot's of feedback but i'm also the author of some lib and know how it is, swimming in my own soup and would be glad someone gave me feedback about my docs.

Also great idea that you cover ts to ts compilation as well when you don't have tsc.

**Comment by fengkx** [comment]
> For me personally, i wouldn't like having some script magically modifying my configs / build chain and i would at least have a manual option.

I have the same concern. I took a quick look at the code. https://github.com/samchon/typia/blob/master/src/executable/TypiaSetupWizard.ts Here.

The setup process first install and use ts-patch instead of the original tsc. Then add the typia transfomer to tsconfig.json and change some compilerOptions( make it more strict).

Document the detail of setup command should be a great.

**Comment by JusttCallMeMike** [comment]
setup process is terrible , it installs ts-patch , doesnt care that you are on 4x and ts-patch works only for 5x . few lines in docs would be perfect.
