### ISSUE TITLE
Support Intersection with Array and Tuple

### ISSUE THREAD

**Issue by luuvish** [samchon/typia#856]
```typescript
import typia from 'typia';

type A = string[] & ['a', 'b'];
const result = typia.validate<A>(['a', 'b']);
```

the iterate_medadata_intersection() reports error message "nonsensible intersection".
This function has not yet been implemented for tuples.
I would like support.

**Comment by samchon** [comment]
It seems nonsensible type for me. Any reason why not using union type instead?

**Comment by luuvish** [comment]
The example above is a condensed code highlighting the problematic sections. The original intention of the code was to create an extended type from the base type, aiming to narrow down the type of the previous property.

```typescript
type Base = {
    kind: string;
    name: string;
    tags: string[];
};

type A = Base & {
    kind: 'A';
    tags: ['A'];
};
type B = Base & {
    kind: 'B';
    tags: ['B'];
};
```

**Comment by samchon** [comment]
```typescript
type Base<Kind extends string, Tags extends string[]> = {
    kind: Kind;
    tags: Tags[];
    name: string;
}
```

Declare like above utilizing the generic arguments, then no problem.

If you want to keep the `Base` type without any generic argument, `Omit<Base, "kind"|"tags">` type is recommended.

Intersection type is not for your case. The intersection type has been designed for below case:

```typescript
interface A {
    a: string;
}
interface B {
    b: boolean;
}
type C = A & B;
```

**Comment by luuvish** [comment]
Typia is already optimizing statements like `string & 'a'` to constant 'a'.
The same goes for `string[] & [string, string]`.
This is a valid syntax in TypeScript, and I'd prefer not to modify such code solely for Typia.

**Comment by samchon** [comment]
You're misunderstanding the `string[] & [string, string]` type.

1. `[string, string]` type enforces the array length to be two
2. `string[]` allows zero length array
4. In that case, `typia` cannot plan validation logic, especially about the array length
5. Therefore, `string[] & [string, string]` is a contradict type within framework of `typia`

I think that as `typia` is a validator library, when contradict type comes so that it is not possible to plan validation logic, `typia` should to inform user to that target type of validation is contradict. Compilation error is one of the delivering the message and let user to know the target type is contradict.

Thus, I recommend you to change the contradict types following the `typia`'s compilation errors.

**Comment by luuvish** [comment]
No, it not contradict type.
string[] ⊃ [string, string] ⊃ ['a', 'b'].
Please, check result of TypeScript type system.

**Comment by samchon** [comment]
I mean the validation logic. If `typia` supports it, about the length check logic, how it should be?

Looking at TypeScript compiler API, especially the `ts.Type` type, it does not directly embody what user has written in the programming code. It emends and re-combines type info considering the relations what you're saying. By the way, in the `ts.Type` data, it does emend the `string[] & [string, string]` type, but just contain the information what user have written itself.

In particular, intersection is a feature that I developed with extra care, as `typia`'s type tag system is related with it. Since `typia` is a validator library, it does not support everything that can be input in simple TS specifications or IDE. Considering the characteristics of the validator's unique story, additional restrictions like your case may be imposed.

**Comment by luuvish** [comment]
I understand that because Typia is a validator library, it's difficult to perform the same type checking as TypeScript.
The intersection issue can probably be resolved by converting it to interface extends.

```typescript
interface Base {
    kind: string;
    name: string;
    tags: string[];
}

interface A extends Base {
    kind: 'A';
    tags: ['A'];
}
interface B extends Base {
    kind: 'B';
    tags: ['B'];
};
```

Thanks to your excellent Typia library, my project seems to be progressing smoothly.
Thank you very much for the detailed explanation.
