### ISSUE TITLE
Standard JSON Schema

### ISSUE THREAD

**Issue by tomwidmer** [samchon/typia#920]
## Feature Request
The current ajv/swagger JSON schema generation relates to OpenAPI/Swagger, not directly to JSON Schema. JSON Schema is a currently evolving almost-standard, although I believe the intention is to standardise it soon with something close to the 2020-12 draft: https://json-schema.org/specification

The `components` field you generate is an OpenAPI/Swagger field, and is not part of a valid JSON schema. Additionally, `nullable` is not a standard json schema field either (and hasn't been in any standard version - it was an OpenAPI 3.0 extension).

It might be good to add in a new option for `json.application` to output a standard JSON schema (along with existing non-standard `ajv` and `swagger` options), perhaps `2020-12`, or the best supported legacy option, which is possibly `draft-07`. AJV supports both of those by the way (although 2020-12 support was incomplete last time I checked). This could just return an array of JSON Schema objects, or you could use the $defs field to put them in a single document if you prefer (see https://json-schema.org/draft/2020-12/json-schema-core#name-schema-re-use-with-defs ).

**Comment by samchon** [comment]
Welcome your PR

**Comment by cAttte** [comment]
hi @samchon, this is still an issue. `typia.json` doesn't generate a plain JSON Schema but an OpenAPI schema. the underlying JSON Schema can be accessed with something like `typia.json.schemas<[Type], "3.1">().schema.components.schema[Type]` but this is very cumbersome, especially when you consider that OpenAPI is just a *user* of JSON Schema, and it doesn't really represent it. **another thing** is that passing just one schema (instead of a tuple) is probably a very common use case. so a much better API would be something like `typia.json.schema<Type>()` and that's it. (this would assume draft 2020 (?), but a Draft type-param could be added in the future if necessary). the good thing is that with this naming, the existing `schemas()` method can be kept (i.e. schema = individual JSON Schema; schemas = OpenAPI schema collection) and no breaking changes are needed.

i can open a PR if that works!

**Comment by samchon** [comment]
As my purpose is to standardizing to `OpenApi.IJsonSchema` type of [`@samchon/openapi`](https://github.com/samchon/openapi) for conversion to LLM function calling schema, I could not understand the requirement of another version of JSON schema specification.

Can you explain me why you required another version?

**Comment by cAttte** [comment]
the OpenAPI specification (and LLMs) just happen to use JSON Schema for their schemas, but JSON Schema is useful for much more than that. one use case is passing it around to other libraries that expect to receive a JSON Schema. these could be validators like [ajv](https://ajv.js.org/) (although i know that the main use case of typia is already validation), or, for example, [JSON Forms](https://jsonforms.io/), which would let you do something like this to easily generate an HTML form based on a TypeScript type:

```tsx
type Form = { firstname: string, lastname: string, age: number }
const App = () => <JsonForms schema={typia.schema<Form>()} />
// without the change: schema={typia.schemas<[Form], "3.1">().schema.components.schema.Form}
```

other use cases are validation for document databases (like MongoDB or Postgres `jsonb`) which might be useful for ORMs and the like, and passing JSON schemas to web API servers or clients that simply don't have access to typia. plain JSON Schema is widely used for a lot of different things. regardless of the use case, JSON Schema isn't really a different "version" from OpenAPI 3.1, it's *the* schema specification which happens to be used and hidden away by OpenAPI. so i think it's pretty important to add first-class support for it **so that users don't have to constantly type `.schema.components.schema[Type]`**, which is very inconvenient and can't be hidden away in a function due to the compile-time nature of typia. so, i only propose a very simple addition that would look something like this (just an example, i'll look into the actual structure when i make the PR):

```ts
export namespace PlainJsonSchemaTransformer {
    export const transform = (props) => {
        const app = JsonSchemasProgrammer.write({ version, metadata })
        const schema = app.components.schema[typeName] // this is what saves the user from typing that out
        return ts.factory.createAsExpression(LiteralFactory.write(schema), ...)
    }
}

// in CallExpressionTransformer:
schema: () => PlainJsonSchemaTransformer.transform()
```

so that the following two will generate the same output:
```ts
const schema = typia.schemas<[Type], "3.1">().schema.components.schema.Type
const schema = typia.schema<Type>()
```

please let me add this feature, it would be very very useful for all JSON Schema users :)
