### ISSUE TITLE
Explicit validation failure in error report

### ISSUE THREAD

**Issue by t3ned** [samchon/typia#953]
## Feature Request

> [Note: this issue orginates from nestia, but it's more suited here](https://github.com/samchon/nestia/issues/785)

### Overview
I'm using nestia configured with the `validate` function for runtime validation in my nestjs applications.

I recently discovered nestia, and everything works great! However, one of the caveats is error handling.

Currently, there is no way to identify exactly what validation stages failed without decoding the value of [`IValidation.IError.expected`](https://github.com/samchon/typia/blob/master/src/IValidation.ts#L18).

I would like to map the error messages to be consistent with the API response structure of my applications. However, that is not possible without writing some sort of decoding algorithm which reads the expected type, and generates a human-readable message.

### Current behaviour
Here's an example error output using the [AOTC example from the nestia docs](https://nestia.io/docs/pure/#aot-compilation):
```json
{
  "errors": [
    {
      "path": "$input.title",
      "expected": "string & MinLength<3>",
      "value": "a"
    },
    {
      "path": "$input.body",
      "expected": "string"
    },
    {
      "path": "$input.files",
      "expected": "Array<IAttachmentFile>",
      "value": 1
    }
  ],
  "message": "Request body data is not following the promised type."
}
```

This is okay, but the [`IValidation.IError.expected`](https://github.com/samchon/typia/blob/master/src/IValidation.ts#L18) value requires some decoding to *humanly* identify that:

* >  `$input.title` must be at least `3` characters long
* >  `$input.body` must be a `string`
* >  `$input.files` must be an `array`

### Proposed solution
It would be great to generate the precise details of a validation error so I can map the errors to a desired message. Here's an example of what that might look like with various types of validations:

```json
{
  "errors": [
    {
      "path": "$input.title",
      "expected": "string & MinLength<3>",
      "value": "a",
      "details": {
        "tag": "MinLength",
        "value": 3
      }
    },
    {
      "path": "$input.body",
      "expected": "string",
      "details": {
        "tag": "BaseType",
        "value": "string"
      }
    },
    {
      "path": "$input.files",
      "expected": "Array<IAttachmentFile>",
      "value": 1,
      "details": {
        "tag": "BaseType",
        "value": "Array"
      }
    }
  ],
  "message": "Request body data is not following the promised type."
}
```

**Comment by samchon** [comment]
https://github.com/samchon/typia/blob/master/test/src/generated/output/createAssert/test_createAssert_ArrayRecursiveUnionExplicit.ts

This is too much repeated issue, and you're considering just a simple type case like `string & MinLength<3>`.

However, the actual world is not such simple as you think. Above link is an example case validting union type, and number of type error cases are infinite, so that it is not possible to trace such detaily as you want. When desining the validation error type structure, we also have to consider not only simple object, but also every compliate types like union, array, tuple, and so on.

At now, just printing the `expected` type and wrong `value` is the simplest way that can express every type error cases. 

Sorry for rejection, but no way in my and your ideas.
