### ISSUE TITLE
Mongoose lean operator not supported by typia

### ISSUE THREAD

**Issue by Yrahate7** [samchon/typia#971]
unsupported type detected

- MongoOptions.ALPNProtocols: (Array<Uint8Array> | Array<string> | Uint8Array | undefined)
  - JSON does not support Uint8Array type.

- MongoOptions.ALPNProtocols: Uint8Array
  - JSON does not support Uint8Array type.

- 'mongoose'.Schema.Types.Boolean.convertToTrue: Set<any>
  - JSON does not support Set type.

- 'mongoose'.Schema.Types.Boolean.convertToFalse: Set<any>
  - JSON does not support Set type.
  
  ============================================
  
  public static async getListSortedByName(this: ReturnModelType<typeof City>) {
		return await this.find({}, {}, { lean: true }).sort({ name: 1 });
}

Current solution is to avoid using lean for this, but doesn't givee the benefits as expected with nestia.

**Comment by samchon** [comment]
It seems like you're using mongoose schema directly as DTO type. 

Why you do not separate DTO from ORM(ODM)? Will you deliver the ORM type with frontend (client) developers? So that the frontend application must install the `mongoose` ODM in their front application? As you're utilizing `nestia` and the purpose of `nestia` is to building and delivering SDK library for the client developers, you've to separate DTO from ORM.

Also, prohibiting `Set`, and `Uint8Array` in the JSON feature is not bug, but actually spec of the JSON.
