### ISSUE TITLE
why typia seem slower than JSON.stringify?

### ISSUE THREAD

**Issue by cesco69** [samchon/typia#974]
I have just tried with a **small object**: 

```ts
import typia from "typia";

export type TestResponse = { 
    name: string;
};
const typiaStringifyFn = typia.json.createStringify<TestResponse>();

console.time('typia')
typiaStringifyFn({ name: 'foo' })
console.timeEnd('typia')

console.time('JSON.stringify')
JSON.stringify({ name: 'foo' })
console.timeEnd('JSON.stringify')
```
result

```shell
typia:          0.025ms
JSON.stringify: 0.008ms
```

I have also triend with a **big object**:

```ts
import typia from "typia";

export type TestResponse = Array<{ name: string }>;
const typiaStringifyFn = typia.json.createStringify<TestResponse>();
const data: TestResponse = Array.from({length: 1000}, (_, i) => ({name: i.toString()}))

console.time('typia')
typiaStringifyFn(data)
console.timeEnd('typia')

console.time('JSON.stringify')
JSON.stringify(data)
console.timeEnd('JSON.stringify')
```

result

```
typia:          0.492ms
JSON.stringify: 0.143ms
```

I have made some mistake?

**Comment by samchon** [comment]
It is because too short time execution so that v8 engine cannot optimize the dedicated scripts.

If the time be increased, the result is different.

The performance different of `typia.json.stringfy()` vs `JSON.stringify()` comes from static accessment vs. dynamic accessment with hidden class optimization. However, your object type has only one property, so that hidden class optimization through static code and structure can't get benefit of it. 

Furthermore, as your program be executed only in the time, so no merit for that case.

In contrary, even no object type be used, if the execution time becomes larger, the result becomes totally different.

```typescript
import typia from "typia";

const REPEAT = 10_000_000;
const VALUE = "something";
const fn = typia.json.createStringify<string>();

const main = async () => {
  console.time("typia.json.stringify()");
  new Array(REPEAT).fill(0).map(() => fn(VALUE));
  console.timeEnd("typia.json.stringify()");

  console.time("JSON.stringify()");
  new Array(REPEAT).fill(0).map(() => JSON.stringify(VALUE));
  console.timeEnd("JSON.stringify()");
}
main().catch(console.error);
```

```bash
typia.json.stringify(): 358.964ms
JSON.stringify(): 1.604s
```

**Comment by samchon** [comment]
Also, I'd updated the `string` to JSON string serialization logic for one year ago, because it is good for totally optimized code.

But I could understand that it is not good for short time execution performance. So, I've changed the string to JSON string serialization logic, so decided to roll back to the previous logic. It may still slower than `JSON.stringify()` function when no optimization be adjusted, but would be a little bit faster.
